# permissions for end users to view foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foo-viewer-role
rules:
- apiGroups:
  - batch.piyush.kubebuilder.io
  resources:
  - foos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.piyush.kubebuilder.io
  resources:
  - foos/status
  verbs:
  - get
